name: React Deployment

on: 
  push:
    branches: [master]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /minh_folder/motion-website
          git fetch origin
          git pull
          npm i
          npm run build
          pm2 reload production
